export enum ActionTypes {
  GET_COUNTER = 'GET_COUNTER',
  SAVE_COUNTER = 'SAVE_COUNTER',
  RESET_COUNTER = 'RESET_COUNTER',
  ADD_ARR_COUNTER = 'ADD_ARR_COUNTER',
  GETING_API = 'GETING_API',
  POSTED_API = 'POSTED_API'
}
